### PR TITLE
Master

### PR DESCRIPTION
**Pull request by TheOnlyMarv**
I added a static method to create a instance of Pixel from the HSV colors.
May that makes it easier to use for some developers.

### CODE REVIEW

**Comment by jakubshark** [comment]
Also please make sure if you are submitting to have a tab spacing of 4.

**Comment by TheOnlyMarv** [comment]
I will do it in the future. Thanks.

**Comment by jakubshark** [comment]
I wanted to ask. What are your opinions on the engine? Are there any changes you think should be made? Any features you would like? You can be as critical as you want, I'm really trying to see where I can improve.

**Comment by TheOnlyMarv** [comment]
I havn't had that much created with the engine yet. So have no idea right now. But i think it will be nice, that developers can write their own shaders if their want.

**Comment by JakubSzark** [comment]
Thank you for the feedback!

**Pull request merged**
